[project]
name = "corp-fin-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=24.10.0",
    "isort>=6.0.0",
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "streamlit>=1.41.1",
    "watchdog>=6.0.0",
]
